export const GamesList = {
  Games: [
    {
    GameName: "Pokémon Alpha Sapphire",
    GameThumbnail: "/game-thumbnails/alphasapphire.png",
    NumberPlayers: 492,
    Platform: "Nintendo 3DS",
    Generation: "6",
    Official: 1,
    Developer: 'GameFreak',
  },
  {
    GameName: "Pokémon Black 2",
    GameThumbnail: "/game-thumbnails/black2.png",
    NumberPlayers: 662,
    Platform: "Nintendo DS",
    Generation: "5",
    Official: 1,
    Developer: 'GameFreak',
  },
  {
    GameName: "Pokémon Crystal",
    GameThumbnail: "/game-thumbnails/crystal.png",
    NumberPlayers: 11,
    Platform: "Game Boy Color",
    Generation: "2",
    Official: 1,
    Developer: 'GameFreak',
  },
  {
    GameName: "Pokémon Emerald",
    GameThumbnail: "/game-thumbnails/emerald.png",
    NumberPlayers: 1200,
    Platform: "Game Boy Advance",
    Generation: "3",
    Official: 1,
    Developer: 'GameFreak',
  },
  {
    GameName: "Pokémon Sacred Gold",
    GameThumbnail: "/game-thumbnails/heartgold.png",
    NumberPlayers: 708,
    Platform: "Nintendo DS",
    Generation: "4",
    Official: 0,
    Developer: 'Drayano',
  },
  {
    GameName: "Pokémon Let's Go Eevee",
    GameThumbnail: "/game-thumbnails/letsgo_eevee.png",
    NumberPlayers: 92,
    Platform: "Nintendo Switch",
    Generation: "7",
    Official: 1,
    Developer: 'GameFreak',
  },
  {
    GameName: "Pokémon Moon",
    GameThumbnail: "/game-thumbnails/moon.png",
    NumberPlayers: 123,
    Platform: "Nintendo 3DS",
    Generation: "7",
    Official: 1,
    Developer: 'GameFreak',
  },
  {
    GameName: "Pokémon Renegade Platinum",
    GameThumbnail: "/game-thumbnails/platinum.png",
    NumberPlayers: 355,
    Platform: "Nintendo DS",
    Generation: "4",
    Official: 0,
    Developer: 'Drayano',
  },
  {
    GameName: "Pokémon Y",
    GameThumbnail: "/game-thumbnails/pokemon_y.png",
    NumberPlayers: 34,
    Platform: "Nintendo 3DS",
    Generation: "6",
    Official: 1,
    Developer: 'GameFreak',
  },
  {
    GameName: "Pokémon Red",
    GameThumbnail: "/game-thumbnails/red.png",
    NumberPlayers: 3,
    Platform: "Game Boy",
    Generation: "1",
    Official: 1,
    Developer: 'GameFreak',
  },
  {
    GameName: "Pokémon Sword",
    GameThumbnail: "/game-thumbnails/sword.png",
    NumberPlayers: 322,
    Platform: "Nintendo Switch",
    Generation: "8",
    Official: 1,
    Developer: 'GameFreak',
  },
  {
    GameName: "Pokémon SuperNova Sun",
    GameThumbnail: "/game-thumbnails/ultrasun.png",
    NumberPlayers: 56,
    Platform: "Nintendo 3DS",
    Generation: "7",
    Official: 0,
    Developer: 'DioVento',
  },
  {
    GameName: "Pokémon Ultra Sun",
    GameThumbnail: "/game-thumbnails/ultrasun.png",
    NumberPlayers: 56,
    Platform: "Nintendo 3DS",
    Generation: "7",
    Official: 1,
    Developer: 'DioVento',
  },
  {
    GameName: "Pokémon Emerald Kaizo",
    GameThumbnail: "/game-thumbnails/emerald.png",
    NumberPlayers: 1759,
    Platform: "Game Boy Advance",
    Generation: "3",
    Official: 0,
    Developer: 'SinisterHoodedFigure',
  },
  {
    GameName: "Pokémon Crystal Clear",
    GameThumbnail: "/game-thumbnails/crystal.png",
    NumberPlayers: 82,
    Platform: "Game Boy Color",
    Generation: "2",
    Official: 0,
    Developer: 'ShockSlayer',
  },
]
}